AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  Exclude:
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "Dangerfile"
    - "node_modules/**/*"
    - "bin/update"
    - "bin/setup"
    - "bin/yarn"
    - "bin/bundle"
    - "config/puma"
    - "bin/webpack"
    - "bin/webpack-dev-server"

LineLength:
  Max: 200

ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'

Metrics/AbcSize:
  Max: 28

MethodLength:
  CountComments: true  # count full line comments?
  Max: 12

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
